sensor:
  - platform: homeassistant
    id: sensor_tr_1
    name: "Technikraum Temperatur - DuscheOben"
    entity_id: sensor.thb1_F05C_temperature

  - platform: template
    name: "Technikraum Temperatur - gemittelt"
    id: sensor_tr
    update_interval: 10s
    filters:
      - median:
          window_size: 5
          send_first_at: 1

    lambda: |-
        return (id(sensor_tr_1).state * 100.0)/100.0;
  - platform: pid
    name: "Technikraum - PID KP"
    type: KP
    climate_id: climate_pid_tr
  - platform: pid
    name: "Technikraum - PID KI"
    type: KI
    climate_id: climate_pid_tr
  - platform: pid
    name: "Technikraum - PID KD"
    type: KD
    climate_id: climate_pid_tr
  - platform: pid
    name: "Technikraum - PID HEAT"
    type: HEAT
    climate_id: climate_pid_tr

climate:
  - platform: pid
    id: climate_pid_tr
    name: "Technikraum Climate PID"
    sensor: sensor_tr
    heat_output: output_tr
    default_target_temperature: 17°C
    control_parameters:
      kp: 0.572962
      ki: 0.00002
      kd: 0.0

output:
  - platform: template
    id: output_tr
    type: float
    write_action:
      - if:
          condition:
            lambda: return ((state == 0.0));
          then:
            - logger.log: "---  ZERO   --- output_tr: write_action triggered with state == 0.0"
          else:
            - logger.log: "-- NON-ZERO --- output_tr: write_action triggered with state <> 0"
      - delay: !lambda "return 24 * 6 / 7 * 60 * 1000;"
      - logger.log: "---  After DELAY  --- setting slow_pwm_tr_1 with state using lambda"
      - output.set_level:
          id: slow_pwm_tr_1
          level: !lambda return state;

  - platform: slow_pwm
    id: slow_pwm_tr_1
    pin:
      number: 33
      inverted: false
      mode:
        output: true
        pulldown: True
    period:
      minutes: 24
    restart_cycle_on_state_change: false
    state_change_action:
        - logger.log: "---  SLOWPWM StateChange --- slow_pwm_tr_1 state changed"
    turn_on_action:
      then:
        - lambda: |-
            id(stellventil_display_7).publish_state(true);
    turn_off_action:
      then:
        - lambda: |-
            id(stellventil_display_7).publish_state(false);


# sensors enabling display of output state in HA
binary_sensor:
  - platform: template
    id: stellventil_display_7
    name: "Stellventil - Oben - 7 - Technikraum"

