sensor:
  - platform: homeassistant
    id: sensor_wz_1
    name: "Wohnzimmer Temperatur - Wohnzimmer"
    entity_id: sensor.thb1_0552_temperature

  - platform: template
    name: "Wohnzimmer Temperatur - gemittelt"
    id: sensor_wz
    update_interval: 10s
    filters:
      - median:
          window_size: 5
          send_first_at: 1

    lambda: |-
        return (id(sensor_wz_1).state * 100.0)/100.0;
  - platform: pid
    name: "Wohnzimmer - PID KP"
    type: KP
    climate_id: climate_pid_wz
  - platform: pid
    name: "Wohnzimmer - PID KI"
    type: KI
    climate_id: climate_pid_wz
  - platform: pid
    name: "Wohnzimmer - PID KD"
    type: KD
    climate_id: climate_pid_wz
  - platform: pid
    name: "Wohnzimmer - PID HEAT"
    type: HEAT
    climate_id: climate_pid_wz

climate:
  - platform: pid
    id: climate_pid_wz
    name: "Wohnzimmer Climate PID"
    sensor: sensor_wz
    heat_output: output_wz
    default_target_temperature: 22°C
    control_parameters:
      kp: 0.572962
      ki: 0.00002
      kd: 0.0

output:
  - platform: template
    id: output_wz
    type: float
    write_action:
      - if:
          condition:
            lambda: return ((state == 0.0));
          then:
            - logger.log: "---  ZERO   --- output_wz: write_action triggered with state == 0.0"
          else:
            - logger.log: "-- NON-ZERO --- output_wz: write_action triggered with state <> 0"
      - delay: !lambda "return 1 * 3 / 8 * 60 * 1000;"
      - logger.log: "---  After DELAY  --- setting slow_pwm_wz_1 with state using lambda"
      - output.set_level:
          id: slow_pwm_wz_1
          level: !lambda return state;
      - if:
          condition:
            lambda: return ((state == 0.0));
          then:
            - logger.log: "---  ZERO   --- output_wz: write_action triggered with state == 0.0"
          else:
            - logger.log: "-- NON-ZERO --- output_wz: write_action triggered with state <> 0"
      - delay: !lambda "return 1 * 4 / 8 * 60 * 1000;"
      - logger.log: "---  After DELAY  --- setting slow_pwm_wz_2 with state using lambda"
      - output.set_level:
          id: slow_pwm_wz_2
          level: !lambda return state;
      - if:
          condition:
            lambda: return ((state == 0.0));
          then:
            - logger.log: "---  ZERO   --- output_wz: write_action triggered with state == 0.0"
          else:
            - logger.log: "-- NON-ZERO --- output_wz: write_action triggered with state <> 0"
      - delay: !lambda "return 1 * 5 / 8 * 60 * 1000;"
      - logger.log: "---  After DELAY  --- setting slow_pwm_wz_3 with state using lambda"
      - output.set_level:
          id: slow_pwm_wz_3
          level: !lambda return state;

  - platform: slow_pwm
    id: slow_pwm_wz_1
    pin:
      number: 14
      inverted: false
      mode:
        output: true
        pulldown: True
    period:
      minutes: 1
    restart_cycle_on_state_change: false
    state_change_action:
        - logger.log: "---  SLOWPWM StateChange --- slow_pwm_wz_1 state changed"
    turn_on_action:
      then:
        - lambda: |-
            id(stellventil_display_3).publish_state(true);
    turn_off_action:
      then:
        - lambda: |-
            id(stellventil_display_3).publish_state(false);

  - platform: slow_pwm
    id: slow_pwm_wz_2
    pin:
      number: 25
      inverted: false
      mode:
        output: true
        pulldown: True
    period:
      minutes: 1
    restart_cycle_on_state_change: false
    state_change_action:
        - logger.log: "---  SLOWPWM StateChange --- slow_pwm_wz_2 state changed"
    turn_on_action:
      then:
        - lambda: |-
            id(stellventil_display_5).publish_state(true);
    turn_off_action:
      then:
        - lambda: |-
            id(stellventil_display_5).publish_state(false);

  - platform: slow_pwm
    id: slow_pwm_wz_3
    pin:
      number: 26
      inverted: false
      mode:
        output: true
        pulldown: True
    period:
      minutes: 1
    restart_cycle_on_state_change: false
    state_change_action:
        - logger.log: "---  SLOWPWM StateChange --- slow_pwm_wz_3 state changed"
    turn_on_action:
      then:
        - lambda: |-
            id(stellventil_display_6).publish_state(true);
    turn_off_action:
      then:
        - lambda: |-
            id(stellventil_display_6).publish_state(false);


# sensors enabling display of output state in HA
binary_sensor:
  - platform: template
    id: stellventil_display_3
    name: "Stellventil - Unten - 3 - Esszimmer"

  - platform: template
    id: stellventil_display_5
    name: "Stellventil - Unten - 5 - WohnzimmerVorn"

  - platform: template
    id: stellventil_display_6
    name: "Stellventil - Unten - 6 - WohnzimmerHinten"

