switch:
  - platform: gpio
    id: relay1
    name: hz01 Relais 1
    pin:
      number: 12
      inverted: True
      mode:
        output: True
        pulldown: True
    on_value:
        - binary_sensor.template.publish:
          id: relay_state_1
          state: id(relay1).state

  - platform: gpio
    id: relay2
    name: hz01 Relais 2
    pin:
      number: 13
      inverted: True
      mode:
        output: True
        pulldown: True
    on_value:
        - binary_sensor.template.publish:
          id: relay_state_2
          state: id(relay2).state

  - platform: gpio
    id: relay3
    name: hz01 Relais 3
    pin:
      number: 14
      inverted: True
      mode:
        output: True
        pulldown: True
    on_value:
        - binary_sensor.template.publish:
          id: relay_state_3
          state: id(relay3).state

  - platform: gpio
    id: relay4
    name: hz01 Relais 4
    pin:
      number: 4
      inverted: True
      mode:
        output: True
        pulldown: True
    on_value:
        - binary_sensor.template.publish:
          id: relay_state_4
          state: id(relay4).state

  - platform: gpio
    id: relay5
    name: hz01 Relais 5
    pin:
      number: 26
      inverted: True
      mode:
        output: True
        pulldown: True
    on_value:
        - binary_sensor.template.publish:
          id: relay_state_5
          state: id(relay5).state

  - platform: gpio
    id: relay6
    name: hz01 Relais 6
    pin:
      number: 25
      inverted: True
      mode:
        output: True
        pulldown: True
    on_value:
        - binary_sensor.template.publish:
          id: relay_state_6
          state: id(relay6).state

  - platform: gpio
    id: relay7
    name: hz01 Relais 7
    pin:
      number: 33
      inverted: True
      mode:
        output: True
        pulldown: True
    on_value:
        - binary_sensor.template.publish:
          id: relay_state_7
          state: id(relay7).state

  - platform: gpio
    id: relay8
    name: hz01 Relais 8
    pin:
      number: 32
      inverted: True
      mode:
        output: True
        pulldown: True
    on_value:
        - binary_sensor.template.publish:
          id: relay_state_8
          state: id(relay8).state


binary_sensor:
  - platform: template
    name: hz01 PID Relais 1
    id: relay_state_1

  - platform: template
    name: hz01 PID Relais 2
    id: relay_state_2

  - platform: template
    name: hz01 PID Relais 3
    id: relay_state_3

  - platform: template
    name: hz01 PID Relais 4
    id: relay_state_4

  - platform: template
    name: hz01 PID Relais 5
    id: relay_state_5

  - platform: template
    name: hz01 PID Relais 6
    id: relay_state_6

  - platform: template
    name: hz01 PID Relais 7
    id: relay_state_7

  - platform: template
    name: hz01 PID Relais 8
    id: relay_state_8
