substitutions:
  friendly_name: hz9
  version: v0.1.8

# v0.1.8: Austausch des Sensors im Sportzimmer vorn (neu 9046, ehemals Mittelgang oben vor Schlafzimmer)

esphome:
  name: heating-9
  friendly_name: heating-9

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "f5YvJmEwtfEGjWWQuaJP2XcoiMOKggHC8WSn3WHwte4="

ota:
  - platform: esphome
    password: "b2d6864b7aa666fcd1e80359aa19dcef"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    gateway: 10.0.0.1
    subnet: 255.255.0.0
    static_ip: 10.0.12.22

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Heating-9 Fallback Hotspot"
    password: "E0AN4LKr4LMk"

captive_portal:

time:
- platform: sntp
  id: sntp_time
  timezone: "Europe/Berlin"

one_wire:
  - platform: gpio
    pin: 17

sensor:
-   platform: dallas_temp
    name: ${friendly_name} Temperatur Vorlauf
    id: bat001_dallas_1
    update_interval: 15s
    address: 0x2a0000073c922928

-   platform: dallas_temp
    name: ${friendly_name} Temperatur Rücklauf
    id: bat001_dallas_2
    update_interval: 15s
    address: 0xec0000072abe7928

-   platform: dallas_temp
    name: ${friendly_name} Temperatur Extra
    id: bat001_dallas_3
    update_interval: 15s
    address: 0x9e0000073cc4d328

packages:
  heizung:
    url: https://github.com/cvstebut/heizung-automation
    files: [area_az.yaml, area_bad.yaml, area_sp.yaml, area_sz.yaml, area_tr.yaml]
    ref: main
    refresh: 1s