
sensor:

  - platform: homeassistant
    id: ha_temp_bad_oben
    name: "Temperatur Bad oben"
    entity_id: sensor.thb1_59e2_temperature
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15

  - platform: homeassistant
    id: ha_temp_bad_oben
    name: "Temperatur Bad oben"
    entity_id: sensor.thb1_bb17_temperature
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15

switch:
  - platform: gpio
    id: relay1
    name: hz01 Relais 1
    pin:
      number: 12
      inverted: True
      mode:
        output: True
        pulldown: True
    on_turn_on:
      then:
       - binary_sensor.template.publish:
          id: relay_state_1
          state: true
    on_turn_off:
      then:
       - binary_sensor.template.publish:
          id: relay_state_1
          state: false

  - platform: gpio
    id: relay2
    name: hz01 Relais 2
    pin:
      number: 13
      inverted: True
      mode:
        output: True
        pulldown: True
    on_turn_on:
      then:
       - binary_sensor.template.publish:
          id: relay_state_2
          state: true
    on_turn_off:
      then:
       - binary_sensor.template.publish:
          id: relay_state_2
          state: false


sensor:

  - platform: homeassistant
    id: ha_temp_bad_oben
    name: "Temperatur Bad oben"
    entity_id: sensor.thb1_921b_temperature
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15

switch:
  - platform: gpio
    id: relay5
    name: hz01 Relais 5
    pin:
      number: 26
      inverted: True
      mode:
        output: True
        pulldown: True
    on_turn_on:
      then:
       - binary_sensor.template.publish:
          id: relay_state_5
          state: true
    on_turn_off:
      then:
       - binary_sensor.template.publish:
          id: relay_state_5
          state: false



